name: Email Notification on Push

on:
  push:
    branches:
      - main

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Send email notification
        uses: peter-evans/sendgrid-action@v1
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          SCRIPT_FILEPATH: .github/email-sending-script.js
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ts03085781@gmail.com
          SUBJECT: 'GitHub Repository Update Notification'
          BODY: |
            A new push has been made to the main branch of your repository.

            Repository: ${{ github.repository }}
            Branch: main
            Commit: ${{ github.sha }}
            Author: ${{ github.actor }}
            Time: ${{ github.event.head_commit.timestamp }}

            You can view the changes here:
            ${{ github.event.head_commit.url }}
