name: Email Notification on Push

on:
  push:
    branches:
      - main

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Send email notification
        uses: licenseware/send-email-notification@v1
        env:
          api-key: ${{ secrets.SENDGRID_API_KEY }}
          from-email: ts03085781@gmail.com
          to-email: ts03085781@gmail.com
          subject: 'GitHub Repository Update Notification'
          markdown-body: |
            A new push has been made to the main branch of your repository.

            Repository: ${{ github.repository }}
            Branch: main
            Commit: ${{ github.sha }}
            Author: ${{ github.actor }}
            Time: ${{ github.event.head_commit.timestamp }}

            You can view the changes here:
            ${{ github.event.head_commit.url }}
